config/routes.rb
Rails.application.routes.draw do
  root "places#index"
  resources :places, only: [:index, :show, :new, :create] do
    resources :ratings, only: [:create, :new]
  end
  devise_for :users, :controllers => { registrations: 'registrations' }

  mount Attachinary::Engine => "/attachinary"

end

app/models/criterion.rb
class Criterion < ActiveRecord::Base
  has_many :detailed_criterions, dependent: :destroy
end

app/models/detailed_criterion.rb
class DetailedCriterion < ActiveRecord::Base
  belongs_to :criterion
  belongs_to :handicap

  def to_h
    {
      name: criterion.name,
      tooltip: self.tooltip
    }
  end
end

app/models/handicap.rb
class Handicap < ActiveRecord::Base
  has_many :detailed_criterions, dependent: :destroy
  has_many :users, dependent: :destroy
end

app/models/place.rb
class Place < ActiveRecord::Base
  has_many :ratings, dependent: :destroy
  geocoded_by :address
  after_validation :geocode, if: :address_changed?
  after_validation :yelpify, if: :address_changed?

  def is_certified?
    certification != "" && !certification.nil?
  end

  def yelpify
    params = {
               term: name[0...50],
               limit: 1
             }

    locale = {
               lang: 'fr'
             }
    if !latitude.nil? && !longitude.nil?
      coordinates = { latitude: latitude, longitude: longitude, accuracy: 1.00 }
      p coordinates, params, locale
      response = Yelp.client.search_by_coordinates(coordinates, params, locale)
      if !response.businesses.empty?
        yelp_id = response.businesses.first.id
      end
    end
  end


  def self.sorted
    all
  end

  def ratings_for(handikey)
    result = Hash.new(nil)
    handicap = Handicap.find_by_handikey(handikey)
    handicap.detailed_criterions.each do |dc|
      result[dc.criterion.name] = []
    end
    self.ratings
    .select { |rating| rating.user.handicap == handicap }
    .each do |review|
      review.details.each do |crit, v|
        result[crit] << v
      end
    end
    result.each do |k, v|
      if v.length == 0
        result[k] = nil
      else
        result[k] = v.reduce(&:+)/v.length
      end
    end
    result
  end

  def average_ratings_by_handicap
    arbh = Hash.new(nil)
    Handicap.all.each do |handicap|
      values = self.ratings
      .select { |rating| rating.user.handicap == handicap }
      .map { |rating| rating.values.reduce(&:+)/rating.values.length }
      if values.length != 0
        arbh[handicap.handikey] = values.reduce(&:+)/values.length
      else
        arbh[handicap.handikey] = nil
      end
    end
    arbh
  end
end

app/models/rating.rb
class Rating < ActiveRecord::Base
  belongs_to :user
  belongs_to :place

  validates :user_id, :uniqueness => { :scope => :place_id }

  def values
    [value1, value2, value3, value4, value5]
  end

  def details
    result = {}
    values.each_with_index do |value, index|
      crit = user.handicap.detailed_criterions[index].criterion.name
      result[crit] = value
    end
    result
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  belongs_to :handicap
  has_many :ratings, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  def name
    "#{fname.capitalize} #{lname[0].upcase}."
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!

  def home
    # TODO // NO HOMEPAGE YET
  end
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  before_action :set_place, only: [:show, :edit, :update, :destroy]
  skip_before_action :authenticate_user!, only: [:index, :show]

  # GET /places
  def index
    @places = Place.sorted
    #if search && !search(params[:search][:term])
      # @yelp_places = Yelp.client.search(params[:search][:term]).businesses
      # TODO : Revoir ça.
    #end
  end

  # GET /places/4
  def show
  end

  # GET /places/new
  def new
    @place = Place.new
  end

=begin
  # GET /places/1/edit
  def edit
  end
=end

  # POST /places
  def create
    @place = Place.new(place_params)

    if @place.save
      redirect_to @place, notice: 'Place was successfully created.'
    else
      render :new
    end
  end

=begin
  # PATCH/PUT /places/1
  def update
    if @place.update(place_params)
      redirect_to @place, notice: 'Place was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /places/1
  def destroy
    @place.destroy
    redirect_to places_url, notice: 'Place was successfully destroyed.'
  end
=end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_place
      @place = Place.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def place_params
      params.require(:place).permit(:name, :address, :latitude, :longitude)
    end
end

app/controllers/ratings_controller.rb
class RatingsController < ApplicationController
#  before_action :set_rating, only: [:show, :edit, :update, :destroy]

=begin
  # GET /ratings
  def index
    @ratings = Rating.all
  end

  # GET /ratings/1
  def show
  end
=end

  # GET /ratings/new
  def new
    @place = get_place
    @rating = current_user.ratings.new
  end

=begin
  # GET /ratings/1/edit
  def edit
  end
=end

  # POST /ratings
  def create
    @place = get_place
    @rating = current_user.ratings.new(rating_params.update(place: @place))
    if @rating.save
      redirect_to @place, notice: "Merci de votre évaluation."
    else
      render :new
    end
  end

=begin
  # PATCH/PUT /ratings/1
  def update
    if @rating.update(rating_params)
      redirect_to @rating, notice: 'Rating was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /ratings/1
  def destroy
    @rating.destroy
    redirect_to ratings_url, notice: 'Rating was successfully destroyed.'
  end
=end

  private
=begin
    # Use callbacks to share common setup or constraints between actions.
    def set_rating
      @rating = Rating.find(params[:id])
    end
=end

    # Never trust parameters from the scary internet, only allow the white list through.
    def rating_params
      params.require(:rating).permit(:value1, :value2, :value3, :value4, :value5, :user_id, :place_id)
    end

    def get_place
      Place.find(params[:place_id])
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:user).permit(:fname, :lname, :email, :password, :password_confirmation, :handicap_id)
  end

  def account_update_params
    params.require(:user).permit(:fname, :lname, :email, :password, :password_confirmation, :handicap_id, :current_password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def color_by_rating(rating)
    if rating.nil?
      return 'grey'
    elsif rating.round == 0
      return 'red'
    elsif rating.round == 1
      return 'orange'
    else
      return 'green'
    end
  end
end

app/helpers/places_helper.rb
module PlacesHelper
  def map_address(place)
    "#{place.address}"
  end

  def full_address(place)
    start = place.name.index("-")
    start ||= -1 # Offsetting the +1
    "#{place.name[(start+1)..-1].strip} #{place.address}"
  end
end

app/helpers/ratings_helper.rb
module RatingsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Mobalib - Votre allié accessibilité.</title>
    <%= csrf_meta_tags %>
    <%= favicon_link_tag 'favicon.png', rel: 'shortcut icon', type: 'image/png' %>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= stylesheet_link_tag "application", params[:controller], :media => "all" %>

  </head>
  <body>
    <%= render 'shared/navbar' %>

    <% if !notice.nil? && !alert.nil? %>
      <%= render 'shared/flashes' %>
    <% end %>

    <%= yield %>

    <%= javascript_include_tag "application", params[:controller] %>
    <%= cloudinary_js_config %>
    <%= yield :after_js %>
  </body>
</html>

app/views/places/_form.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-offset-2 col-md-8">
      <%= simple_form_for(@place) do |f| %>
        <%= f.error_notification %>

        <div class="form-inputs">
          <%= f.input :name, input_html: { id: "name_autocomplete" } %>
          <%= f.input :address, input_html: { id: "address_autocomplete" } %>
        </div>

        <div class="form-actions">
          <%= f.button :submit %>
        </div>
      <% end %>
    </div>
  </div>
</div>


<% content_for :after_js do %>
  <script type="text/javascript"
    src="https://maps.googleapis.com/maps/api/js?libraries=places&key=<%= ENV['GOOGLE_API_KEY'] %>">
  </script>

  <script>
    function initializeAutocomplete(id) {
      var element = document.getElementById(id);
      if (element) {
        var autocomplete = new google.maps.places.Autocomplete(element,
          { bounds: new google.maps.LatLngBounds(new google.maps.LatLng(44.910825, -0.485052), new google.maps.LatLng(44.769138, -0.683853)) }
          );
        // Bounds are Bordeaux, defined by hand on Google Maps - how neat. #DIRTYFIX
        google.maps.event.addListener(autocomplete, 'place_changed', onPlaceChanged);
      }
    }

    function onPlaceChanged() {
      var place = this.getPlace();
      console.log(place);
      document.getElementById('name_autocomplete').value = place.name;
      document.getElementById('address_autocomplete').value = place.formatted_address;
    }

    google.maps.event.addDomListener(window, 'load', function() {
      initializeAutocomplete('name_autocomplete');
      initializeAutocomplete('address_autocomplete');
    });
  </script>
<% end %>

app/views/places/edit.html.erb
<h1>Editing Place</h1>

<%= render 'form' %>

<%= link_to 'Show', @place %> |
<%= link_to 'Back', places_path %>

app/views/places/index.html.erb
<div class="container-fluid">
  <div class="row">
    <% @places.each do |place| %>
      <%= link_to place do %>
        <div class="col-xs-12 col-sm-6 col-md-4">
          <div class="height-card square-corners white shadowed flex medium-margin">
            <%# cl_image_tag place.photo.path, width: 300, height: 300, crop: :lfill, alt: "Photo de #{place.name}", class: "flex-left no-margins" %>
            <img src="http://placehold.it/150/tech" class="hidden-mobile" style="width: 150px; height: 150px;">
            <div class="flex-expand flex column">
              <div class="flex-expand">
                <h2 class="name-sized"><%= place.name %></h2>
                <p><%= place.address %></p>
              </div>
              <div class="space-around">
                <% place.average_ratings_by_handicap.each do |handikey, rating| %>
                  <div class="handicon handicon-small icon-handi-<%= handikey %> <%= color_by_rating(rating) %> rounded-corners center medium-margin-bottom">
                  </div>
                <% end %>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

<%# TODO: INSERT MAP %>
<%# TODO: DISPLAY YELP DATA %>

app/views/places/new.html.erb
<h1>Indiquez un endroit.</h1>

<%= render 'form' %>

app/views/places/show.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-sm-8 height-half-screen">
      <h2><%= @place.name %></h2>
      <p><%= @place.address %></p>
      <% if @place.yelp_id %>
        <p>Yelp data goes here.</p>
      <% end %>
      <div class="absolutely-top absolutely-right">
        <%= icon("universal-access") %>
        <p>Validé par le label Tourisme-Handicap</p>
      </div>
    </div>
    <div class="col-sm-4 center height-half-screen">
      <div class="full-width flex space-around">
        <% @place.average_ratings_by_handicap.each do |handikey, rating| %>
          <div class="flex column">
            <div class="handicon handicon-small icon-handi-<%= handikey %> <%= color_by_rating(rating) %> rounded-corners medium-margin-bottom center">
            </div>
            <div class="flex column center">
              <% @place.ratings_for(handikey).each do |criterion, score| %>
                <div class="handicon handicon-small <%= color_by_rating(score) %> rounded-corners flex center small-margin-bottom center">
                  <%= criterion.first %>
                </div>
              <% end %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
    <div class="col-sm-4 col-sm-push-8 no-padding height-half-screen">
      <% if @place.latitude && @place.longitude %>
        <iframe
          width="100%"
          height="100%"
          frameborder="0" style="border:0"
          src="https://www.google.com/maps/embed/v1/place?key=<%= ENV['GOOGLE_API_KEY'] %>&q=<%= URI.encode(map_address(@place)).downcase %>"
          allowfullscreen>
        </iframe>
    <% else %>
      <div class="column full-height center">
        <p>Attention !</p>
        <p>Nous ne pouvons localiser l'addresse.</p>
      </div>
    <% end %>
    </div>
    <div class="col-sm-pull-4 col-sm-8 height-half-screen">
      <% if @place.ratings.blank? %>
        <div class="column full-height center">
          <p>Pas encore de reviews. </p>
          <p><%= link_to "Laissez nous votre avis !", new_place_rating_path(@place) %></p>
        </div>
      <% else %>
        <div class="column scrollable">
          <% if user_signed_in? && !@place.ratings.find { |r| r.user == current_user } %>
            <div class="center column full-width top-bordered square-corners white medium-padding small-padding-top">
              <p><%= link_to "Laissez nous votre avis !", new_place_rating_path(@place) %></p>
            </div>
          <% end %>
          <% @place.ratings.each do |rating| %>
            <div class="center column full-width top-bordered square-corners white medium-padding small-padding-top">
              <div class="name-sized medium-margin-bottom full-width">
                <%= rating.user.fname %> <%= rating.user.lname.first %>
              </div>
              <div class="full-width center">
                <% rating.details.each do |crit, value| %>
                  <div class="handicon handicon-small icon-handi-<%= crit %> <%= color_by_rating(value) %> rounded-corners small-margin-side center flex flex-left"><%= crit.first %></div>
                <% end %>
              </div>
            </div>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/ratings/_form.html.erb
<%= simple_form_for [@place, @rating] do |f| %>
  <%= f.error_notification %>

  <div class="container-fluid">
    <div class="row">
      <% current_user.handicap.detailed_criterions.each_with_index do |crit, i| %>
        <% if i == 0 %>
          <div class="col-sm-2 col-sm-offset-1 center">
        <% else %>
          <div class="col-sm-2 center">
        <% end %>
        <%= f.input "value#{i+1}".to_sym, as: :radio_buttons, label: crit.criterion.name, error: false do%>
          <div class="center">
            <%= f.collection_radio_buttons "value#{i+1}", (0..2), :to_i, :next, boolean_style: :inline, item_wrapper_tag: :div do |b| %>
              <%= b.radio_button class: 'hidden-input' %>
              <%= b.label do %>
                <div class="clickable handicon handicon-small <%= color_by_rating(b.value) %> rounded-corners center medium-margin-bottom">
                  <%= b.value %>
                </div>
              <% end %>
            <% end %>
          </div>
        <% end %>
        </div>
      <% end %>

    </div>
    <div class="form-actions center">
      <%= f.button :submit %>
    </div>
  </div>
  <% end %>

app/views/ratings/edit.html.erb
<h1>Editing Rating</h1>

<%= render 'form' %>

<%= link_to 'Show', @rating %> |
<%= link_to 'Back', ratings_path %>

app/views/ratings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Ratings</h1>

<table>
  <thead>
    <tr>
      <th>Value</th>
      <th>User</th>
      <th>Place</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ratings.each do |rating| %>
      <tr>
        <td><%= rating.value %></td>
        <td><%= rating.user %></td>
        <td><%= rating.place %></td>
        <td><%= link_to 'Show', rating %></td>
        <td><%= link_to 'Edit', edit_rating_path(rating) %></td>
        <td><%= link_to 'Destroy', rating, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Rating', new_rating_path %>

app/views/ratings/new.html.erb
<h1 class="center">Laissez votre avis.</h1>

<%= render 'form' %>

app/views/ratings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Value:</strong>
  <%= @rating.value %>
</p>

<p>
  <strong>User:</strong>
  <%= @rating.user %>
</p>

<p>
  <strong>Place:</strong>
  <%= @rating.place %>
</p>

<%= link_to 'Edit', edit_rating_path(@rating) %> |
<%= link_to 'Back', ratings_path %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "mobalib.jpg" %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <!-- Different navigation if login or not -->
    <% if user_signed_in? %>

      <!-- Profile picture and dropdown -->
      <%= link_to t(".sign_in", default: "Postez un lieu"), new_place_path, class: "navbar-wagon-item navbar-wagon-button" %>
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <%= image_tag "http://placehold.it/30x30", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-user"></i> <%= t ".profile", default: "Profile" %>
              <% end %>
            </li>
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-home"></i>  <%= t ".profile", default: "Home" %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t ".sign_out", default: "Log out" %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>

    <% else %>

      <!-- Login text link -->
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-button" %>

    <% end %>

    <!-- Button (call-to-action) -->
    <%#= link_to t(".top_call_to_action", default: "Post stuff"), "#", class: "navbar-wagon-item navbar-wagon-button btn" %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li>
          <%= link_to "#" do %>
            <i class="fa fa-user"></i> <%= t ".profile", default: "Profile" %>
          <% end %>
        </li>
        <li>
          <%= link_to "#" do %>
            <i class="fa fa-home"></i>  <%= t ".profile", default: "Home" %>
          <% end %>
        </li>
        <li>
          <%= link_to destroy_user_session_path, method: :delete do %>
            <i class="fa fa-sign-out"></i>  <%= t ".sign_out", default: "Log out" %>
          <% end %>
        </li>
      </ul>
    </div>
  </div>
</div>